import Head from 'next/head';
import React from 'react';

const MetaTitle = ({ title }: { title: string }) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by Rick and Morty API" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/icon.ico" />
        </Head>
    );
};

export default MetaTitle;
